/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 94
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_IDENT = 1,
  anon_sym_import = 2,
  anon_sym_DOT = 3,
  anon_sym_SEMI = 4,
  anon_sym_LBRACK = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACK = 7,
  anon_sym_DASH_GT = 8,
  anon_sym_QMARK = 9,
  anon_sym_BANG = 10,
  anon_sym_COLON = 11,
  anon_sym_const = 12,
  anon_sym_inline = 13,
  anon_sym_func = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_end = 17,
  anon_sym_i8 = 18,
  anon_sym_i16 = 19,
  anon_sym_i32 = 20,
  anon_sym_i64 = 21,
  anon_sym_u8 = 22,
  anon_sym_u16 = 23,
  anon_sym_u32 = 24,
  anon_sym_u64 = 25,
  anon_sym_usize = 26,
  anon_sym_isize = 27,
  anon_sym_f32 = 28,
  anon_sym_f64 = 29,
  anon_sym_bool = 30,
  anon_sym_char = 31,
  anon_sym_str = 32,
  anon_sym_STAR = 33,
  sym_line_comment = 34,
  sym_pub = 35,
  sym_program = 36,
  sym_item = 37,
  sym_import_def = 38,
  sym_type_params = 39,
  sym_type_param = 40,
  sym_result = 41,
  sym_params = 42,
  sym_param = 43,
  sym_block = 44,
  sym_function = 45,
  sym_statement = 46,
  sym_type = 47,
  aux_sym_program_repeat1 = 48,
  aux_sym_import_def_repeat1 = 49,
  aux_sym_type_params_repeat1 = 50,
  aux_sym_params_repeat1 = 51,
  aux_sym_block_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_IDENT] = "IDENT",
  [anon_sym_import] = "import",
  [anon_sym_DOT] = ".",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_QMARK] = "\?",
  [anon_sym_BANG] = "!",
  [anon_sym_COLON] = ":",
  [anon_sym_const] = "const",
  [anon_sym_inline] = "inline",
  [anon_sym_func] = "func",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_end] = "end",
  [anon_sym_i8] = "i8",
  [anon_sym_i16] = "i16",
  [anon_sym_i32] = "i32",
  [anon_sym_i64] = "i64",
  [anon_sym_u8] = "u8",
  [anon_sym_u16] = "u16",
  [anon_sym_u32] = "u32",
  [anon_sym_u64] = "u64",
  [anon_sym_usize] = "usize",
  [anon_sym_isize] = "isize",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [anon_sym_bool] = "bool",
  [anon_sym_char] = "char",
  [anon_sym_str] = "str",
  [anon_sym_STAR] = "*",
  [sym_line_comment] = "line_comment",
  [sym_pub] = "pub",
  [sym_program] = "program",
  [sym_item] = "item",
  [sym_import_def] = "import_def",
  [sym_type_params] = "type_params",
  [sym_type_param] = "type_param",
  [sym_result] = "result",
  [sym_params] = "params",
  [sym_param] = "param",
  [sym_block] = "block",
  [sym_function] = "function",
  [sym_statement] = "statement",
  [sym_type] = "type",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_import_def_repeat1] = "import_def_repeat1",
  [aux_sym_type_params_repeat1] = "type_params_repeat1",
  [aux_sym_params_repeat1] = "params_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_IDENT] = sym_IDENT,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_inline] = anon_sym_inline,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_i8] = anon_sym_i8,
  [anon_sym_i16] = anon_sym_i16,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_usize] = anon_sym_usize,
  [anon_sym_isize] = anon_sym_isize,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_char] = anon_sym_char,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_line_comment] = sym_line_comment,
  [sym_pub] = sym_pub,
  [sym_program] = sym_program,
  [sym_item] = sym_item,
  [sym_import_def] = sym_import_def,
  [sym_type_params] = sym_type_params,
  [sym_type_param] = sym_type_param,
  [sym_result] = sym_result,
  [sym_params] = sym_params,
  [sym_param] = sym_param,
  [sym_block] = sym_block,
  [sym_function] = sym_function,
  [sym_statement] = sym_statement,
  [sym_type] = sym_type,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_import_def_repeat1] = aux_sym_import_def_repeat1,
  [aux_sym_type_params_repeat1] = aux_sym_type_params_repeat1,
  [aux_sym_params_repeat1] = aux_sym_params_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_IDENT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inline] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_usize] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_isize] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_char] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_pub] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_import_def] = {
    .visible = true,
    .named = true,
  },
  [sym_type_params] = {
    .visible = true,
    .named = true,
  },
  [sym_type_param] = {
    .visible = true,
    .named = true,
  },
  [sym_result] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_def_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '!', 11,
        '(', 13,
        ')', 14,
        '*', 15,
        ',', 7,
        '-', 2,
        '.', 4,
        '/', 1,
        ':', 12,
        ';', 5,
        '?', 10,
        '[', 6,
        ']', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == '/') ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(9);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_IDENT);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'b', 1,
        'c', 2,
        'e', 3,
        'f', 4,
        'i', 5,
        'p', 6,
        's', 7,
        'u', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'h') ADVANCE(10);
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == '3') ADVANCE(13);
      if (lookahead == '6') ADVANCE(14);
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == '1') ADVANCE(16);
      if (lookahead == '3') ADVANCE(17);
      if (lookahead == '6') ADVANCE(18);
      if (lookahead == '8') ADVANCE(19);
      if (lookahead == 'm') ADVANCE(20);
      if (lookahead == 'n') ADVANCE(21);
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == '1') ADVANCE(25);
      if (lookahead == '3') ADVANCE(26);
      if (lookahead == '6') ADVANCE(27);
      if (lookahead == '8') ADVANCE(28);
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(33);
      END_STATE();
    case 13:
      if (lookahead == '2') ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead == '4') ADVANCE(35);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 16:
      if (lookahead == '6') ADVANCE(37);
      END_STATE();
    case 17:
      if (lookahead == '2') ADVANCE(38);
      END_STATE();
    case 18:
      if (lookahead == '4') ADVANCE(39);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_i8);
      END_STATE();
    case 20:
      if (lookahead == 'p') ADVANCE(40);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 23:
      if (lookahead == 'b') ADVANCE(43);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 25:
      if (lookahead == '6') ADVANCE(45);
      END_STATE();
    case 26:
      if (lookahead == '2') ADVANCE(46);
      END_STATE();
    case 27:
      if (lookahead == '4') ADVANCE(47);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_u8);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(51);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_f64);
      END_STATE();
    case 36:
      if (lookahead == 'c') ADVANCE(52);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_i16);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 40:
      if (lookahead == 'o') ADVANCE(53);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(54);
      END_STATE();
    case 42:
      if (lookahead == 'z') ADVANCE(55);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_pub);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_str);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_u16);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_u32);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_u64);
      END_STATE();
    case 48:
      if (lookahead == 'z') ADVANCE(56);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_char);
      END_STATE();
    case 51:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(59);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(62);
      END_STATE();
    case 59:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_isize);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_usize);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_inline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_IDENT] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_inline] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_i8] = ACTIONS(1),
    [anon_sym_i16] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_usize] = ACTIONS(1),
    [anon_sym_isize] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_char] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_pub] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(67),
    [sym_item] = STATE(9),
    [sym_import_def] = STATE(22),
    [sym_function] = STATE(22),
    [aux_sym_program_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_inline] = ACTIONS(9),
    [anon_sym_func] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(3),
    [sym_pub] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      anon_sym_QMARK,
    ACTIONS(17), 1,
      anon_sym_const,
    ACTIONS(21), 1,
      anon_sym_STAR,
    STATE(59), 1,
      sym_type,
    ACTIONS(19), 15,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
  [33] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(21), 1,
      anon_sym_STAR,
    ACTIONS(23), 1,
      anon_sym_QMARK,
    STATE(58), 1,
      sym_type,
    ACTIONS(19), 15,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
  [63] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(21), 1,
      anon_sym_STAR,
    ACTIONS(25), 1,
      anon_sym_const,
    STATE(65), 1,
      sym_type,
    ACTIONS(19), 15,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
  [93] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(21), 1,
      anon_sym_STAR,
    STATE(65), 1,
      sym_type,
    ACTIONS(19), 15,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
  [120] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(21), 1,
      anon_sym_STAR,
    STATE(26), 1,
      sym_type,
    ACTIONS(19), 15,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
  [147] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(21), 1,
      anon_sym_STAR,
    STATE(76), 1,
      sym_type,
    ACTIONS(19), 15,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
  [174] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(21), 1,
      anon_sym_STAR,
    STATE(66), 1,
      sym_type,
    ACTIONS(19), 15,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_usize,
      anon_sym_isize,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_bool,
      anon_sym_char,
      anon_sym_str,
  [201] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_inline,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      sym_pub,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(10), 2,
      sym_item,
      aux_sym_program_repeat1,
    STATE(22), 2,
      sym_import_def,
      sym_function,
  [228] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      anon_sym_import,
    ACTIONS(34), 1,
      anon_sym_inline,
    ACTIONS(37), 1,
      anon_sym_func,
    ACTIONS(40), 1,
      sym_pub,
    STATE(10), 2,
      sym_item,
      aux_sym_program_repeat1,
    STATE(22), 2,
      sym_import_def,
      sym_function,
  [255] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(43), 1,
      anon_sym_DASH_GT,
    ACTIONS(45), 1,
      anon_sym_end,
    STATE(35), 1,
      sym_result,
    STATE(70), 1,
      sym_block,
    STATE(48), 2,
      sym_statement,
      aux_sym_block_repeat1,
  [275] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(43), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_end,
    STATE(34), 1,
      sym_result,
    STATE(71), 1,
      sym_block,
    STATE(48), 2,
      sym_statement,
      aux_sym_block_repeat1,
  [295] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(43), 1,
      anon_sym_DASH_GT,
    ACTIONS(49), 1,
      anon_sym_end,
    STATE(29), 1,
      sym_result,
    STATE(87), 1,
      sym_block,
    STATE(48), 2,
      sym_statement,
      aux_sym_block_repeat1,
  [315] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(43), 1,
      anon_sym_DASH_GT,
    ACTIONS(51), 1,
      anon_sym_end,
    STATE(36), 1,
      sym_result,
    STATE(89), 1,
      sym_block,
    STATE(48), 2,
      sym_statement,
      aux_sym_block_repeat1,
  [335] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(43), 1,
      anon_sym_DASH_GT,
    ACTIONS(53), 1,
      anon_sym_end,
    STATE(33), 1,
      sym_result,
    STATE(84), 1,
      sym_block,
    STATE(48), 2,
      sym_statement,
      aux_sym_block_repeat1,
  [355] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(55), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_inline,
      anon_sym_func,
      sym_pub,
  [366] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(57), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_inline,
      anon_sym_func,
      sym_pub,
  [377] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(59), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_inline,
      anon_sym_func,
      sym_pub,
  [388] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(61), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_inline,
      anon_sym_func,
      sym_pub,
  [399] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(63), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_inline,
      anon_sym_func,
      sym_pub,
  [410] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(65), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_inline,
      anon_sym_func,
      sym_pub,
  [421] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(67), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_inline,
      anon_sym_func,
      sym_pub,
  [432] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(69), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_inline,
      anon_sym_func,
      sym_pub,
  [443] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(71), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_inline,
      anon_sym_func,
      sym_pub,
  [454] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(73), 5,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_inline,
      anon_sym_func,
      sym_pub,
  [465] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(75), 4,
      anon_sym_COMMA,
      anon_sym_BANG,
      anon_sym_RPAREN,
      anon_sym_end,
  [475] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(77), 1,
      sym_IDENT,
    ACTIONS(79), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_param,
    STATE(90), 1,
      sym_params,
  [491] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(77), 1,
      sym_IDENT,
    ACTIONS(81), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_param,
    STATE(88), 1,
      sym_params,
  [507] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(47), 1,
      anon_sym_end,
    STATE(71), 1,
      sym_block,
    STATE(48), 2,
      sym_statement,
      aux_sym_block_repeat1,
  [521] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(83), 4,
      anon_sym_COMMA,
      anon_sym_BANG,
      anon_sym_RPAREN,
      anon_sym_end,
  [531] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(77), 1,
      sym_IDENT,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_param,
    STATE(80), 1,
      sym_params,
  [547] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(77), 1,
      sym_IDENT,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_param,
    STATE(82), 1,
      sym_params,
  [563] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(51), 1,
      anon_sym_end,
    STATE(89), 1,
      sym_block,
    STATE(48), 2,
      sym_statement,
      aux_sym_block_repeat1,
  [577] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_end,
    STATE(84), 1,
      sym_block,
    STATE(48), 2,
      sym_statement,
      aux_sym_block_repeat1,
  [591] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(49), 1,
      anon_sym_end,
    STATE(87), 1,
      sym_block,
    STATE(48), 2,
      sym_statement,
      aux_sym_block_repeat1,
  [605] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(89), 1,
      anon_sym_end,
    STATE(92), 1,
      sym_block,
    STATE(48), 2,
      sym_statement,
      aux_sym_block_repeat1,
  [619] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      sym_IDENT,
    ACTIONS(93), 1,
      anon_sym_RBRACK,
    STATE(56), 1,
      sym_type_param,
  [632] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      sym_IDENT,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
    STATE(56), 1,
      sym_type_param,
  [645] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(97), 1,
      anon_sym_LBRACK,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
    STATE(73), 1,
      sym_type_params,
  [658] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
    ACTIONS(101), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      aux_sym_type_params_repeat1,
  [671] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(103), 1,
      anon_sym_end,
    STATE(41), 2,
      sym_statement,
      aux_sym_block_repeat1,
  [682] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(105), 1,
      anon_sym_DOT,
    ACTIONS(108), 1,
      anon_sym_SEMI,
    STATE(42), 1,
      aux_sym_import_def_repeat1,
  [695] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(110), 1,
      anon_sym_COMMA,
    ACTIONS(113), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      aux_sym_type_params_repeat1,
  [708] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(77), 1,
      sym_IDENT,
    ACTIONS(115), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      sym_param,
  [721] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(117), 1,
      anon_sym_COMMA,
    ACTIONS(120), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_params_repeat1,
  [734] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(97), 1,
      anon_sym_LBRACK,
    ACTIONS(122), 1,
      anon_sym_LPAREN,
    STATE(86), 1,
      sym_type_params,
  [747] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    ACTIONS(126), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      aux_sym_type_params_repeat1,
  [760] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(128), 1,
      anon_sym_end,
    STATE(41), 2,
      sym_statement,
      aux_sym_block_repeat1,
  [771] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(97), 1,
      anon_sym_LBRACK,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    STATE(81), 1,
      sym_type_params,
  [784] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(132), 1,
      anon_sym_DOT,
    ACTIONS(134), 1,
      anon_sym_SEMI,
    STATE(51), 1,
      aux_sym_import_def_repeat1,
  [797] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(132), 1,
      anon_sym_DOT,
    ACTIONS(136), 1,
      anon_sym_SEMI,
    STATE(42), 1,
      aux_sym_import_def_repeat1,
  [810] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(138), 1,
      anon_sym_COMMA,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_params_repeat1,
  [823] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(77), 1,
      sym_IDENT,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      sym_param,
  [836] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    STATE(45), 1,
      aux_sym_params_repeat1,
  [849] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(77), 1,
      sym_IDENT,
    STATE(60), 1,
      sym_param,
  [859] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(113), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [867] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      sym_IDENT,
    STATE(47), 1,
      sym_type_param,
  [877] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(146), 1,
      anon_sym_BANG,
    ACTIONS(148), 1,
      anon_sym_end,
  [887] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(150), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [895] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(120), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [903] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(108), 2,
      anon_sym_DOT,
      anon_sym_SEMI,
  [911] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(152), 1,
      anon_sym_inline,
    ACTIONS(154), 1,
      anon_sym_func,
  [921] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      sym_IDENT,
    STATE(56), 1,
      sym_type_param,
  [931] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(156), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [939] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(158), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [947] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(160), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [955] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
  [962] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(164), 1,
      sym_IDENT,
  [969] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(166), 1,
      anon_sym_func,
  [976] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(49), 1,
      anon_sym_end,
  [983] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_end,
  [990] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(154), 1,
      anon_sym_func,
  [997] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
  [1004] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
  [1011] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(170), 1,
      sym_IDENT,
  [1018] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(172), 1,
      anon_sym_end,
  [1025] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(174), 1,
      sym_IDENT,
  [1032] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(172), 1,
      anon_sym_end,
  [1039] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(176), 1,
      sym_IDENT,
  [1046] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(79), 1,
      anon_sym_RPAREN,
  [1053] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(178), 1,
      anon_sym_LPAREN,
  [1060] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
  [1067] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(182), 1,
      sym_IDENT,
  [1074] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(51), 1,
      anon_sym_end,
  [1081] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(184), 1,
      anon_sym_COLON,
  [1088] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(99), 1,
      anon_sym_LPAREN,
  [1095] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(47), 1,
      anon_sym_end,
  [1102] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
  [1109] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(89), 1,
      anon_sym_end,
  [1116] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
  [1123] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(186), 1,
      anon_sym_LPAREN,
  [1130] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(188), 1,
      anon_sym_end,
  [1137] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(190), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 63,
  [SMALL_STATE(5)] = 93,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 147,
  [SMALL_STATE(8)] = 174,
  [SMALL_STATE(9)] = 201,
  [SMALL_STATE(10)] = 228,
  [SMALL_STATE(11)] = 255,
  [SMALL_STATE(12)] = 275,
  [SMALL_STATE(13)] = 295,
  [SMALL_STATE(14)] = 315,
  [SMALL_STATE(15)] = 335,
  [SMALL_STATE(16)] = 355,
  [SMALL_STATE(17)] = 366,
  [SMALL_STATE(18)] = 377,
  [SMALL_STATE(19)] = 388,
  [SMALL_STATE(20)] = 399,
  [SMALL_STATE(21)] = 410,
  [SMALL_STATE(22)] = 421,
  [SMALL_STATE(23)] = 432,
  [SMALL_STATE(24)] = 443,
  [SMALL_STATE(25)] = 454,
  [SMALL_STATE(26)] = 465,
  [SMALL_STATE(27)] = 475,
  [SMALL_STATE(28)] = 491,
  [SMALL_STATE(29)] = 507,
  [SMALL_STATE(30)] = 521,
  [SMALL_STATE(31)] = 531,
  [SMALL_STATE(32)] = 547,
  [SMALL_STATE(33)] = 563,
  [SMALL_STATE(34)] = 577,
  [SMALL_STATE(35)] = 591,
  [SMALL_STATE(36)] = 605,
  [SMALL_STATE(37)] = 619,
  [SMALL_STATE(38)] = 632,
  [SMALL_STATE(39)] = 645,
  [SMALL_STATE(40)] = 658,
  [SMALL_STATE(41)] = 671,
  [SMALL_STATE(42)] = 682,
  [SMALL_STATE(43)] = 695,
  [SMALL_STATE(44)] = 708,
  [SMALL_STATE(45)] = 721,
  [SMALL_STATE(46)] = 734,
  [SMALL_STATE(47)] = 747,
  [SMALL_STATE(48)] = 760,
  [SMALL_STATE(49)] = 771,
  [SMALL_STATE(50)] = 784,
  [SMALL_STATE(51)] = 797,
  [SMALL_STATE(52)] = 810,
  [SMALL_STATE(53)] = 823,
  [SMALL_STATE(54)] = 836,
  [SMALL_STATE(55)] = 849,
  [SMALL_STATE(56)] = 859,
  [SMALL_STATE(57)] = 867,
  [SMALL_STATE(58)] = 877,
  [SMALL_STATE(59)] = 887,
  [SMALL_STATE(60)] = 895,
  [SMALL_STATE(61)] = 903,
  [SMALL_STATE(62)] = 911,
  [SMALL_STATE(63)] = 921,
  [SMALL_STATE(64)] = 931,
  [SMALL_STATE(65)] = 939,
  [SMALL_STATE(66)] = 947,
  [SMALL_STATE(67)] = 955,
  [SMALL_STATE(68)] = 962,
  [SMALL_STATE(69)] = 969,
  [SMALL_STATE(70)] = 976,
  [SMALL_STATE(71)] = 983,
  [SMALL_STATE(72)] = 990,
  [SMALL_STATE(73)] = 997,
  [SMALL_STATE(74)] = 1004,
  [SMALL_STATE(75)] = 1011,
  [SMALL_STATE(76)] = 1018,
  [SMALL_STATE(77)] = 1025,
  [SMALL_STATE(78)] = 1032,
  [SMALL_STATE(79)] = 1039,
  [SMALL_STATE(80)] = 1046,
  [SMALL_STATE(81)] = 1053,
  [SMALL_STATE(82)] = 1060,
  [SMALL_STATE(83)] = 1067,
  [SMALL_STATE(84)] = 1074,
  [SMALL_STATE(85)] = 1081,
  [SMALL_STATE(86)] = 1088,
  [SMALL_STATE(87)] = 1095,
  [SMALL_STATE(88)] = 1102,
  [SMALL_STATE(89)] = 1109,
  [SMALL_STATE(90)] = 1116,
  [SMALL_STATE(91)] = 1123,
  [SMALL_STATE(92)] = 1130,
  [SMALL_STATE(93)] = 1137,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 7, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 11, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_def, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 5, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 6, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_def, 4, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 8, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 9, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 10, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_def_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_def_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_params_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_params_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 3, 0, 0),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_result, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_param, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 5, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_params, 5, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_result, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_params, 4, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_params, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bedrock(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_IDENT,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bedrock",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
